# Generated by Django 4.1.1 on 2022-09-14 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("date_requested", models.DateField()),
                ("status", models.CharField(max_length=50)),
                ("date_completed", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50)),
                ("business_unit", models.CharField(max_length=50)),
                ("description", models.TextField()),
                ("main_contact_number", models.CharField(max_length=18)),
                (
                    "parent_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="child_services",
                        to="main.service",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contact",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("is_approver", models.BooleanField()),
                ("contact_number", models.CharField(max_length=18)),
                (
                    "line_manager",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff",
                        to="main.contact",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.service"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChangeRequestUpdate",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("text", models.TextField()),
                (
                    "change_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="main.changerequest",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="changerequest",
            name="approver",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="approver_changes",
                to="main.contact",
            ),
        ),
        migrations.AddField(
            model_name="changerequest",
            name="requestor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="requestor_changes",
                to="main.contact",
            ),
        ),
    ]
