# Generated by Django 4.1.1 on 2022-09-21 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Contact",
            new_name="Requestor",
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="date_completed",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="business_unit",
            field=models.CharField(
                choices=[
                    ("Group", "Group"),
                    ("Insight Healthcare", "Insight Healthcare"),
                    ("Mental Health Concern", "Mental Health Concern"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="service",
            name="main_contact_number",
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
    ]
