# Generated by Django 4.1.1 on 2022-09-24 15:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_alter_changerequest_date_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequestupdate",
            name="date_time_posted",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Clinical Assessment", "Clinical Assessment"),
                    ("Awaiting Prioritisation", "Awaiting Prioritisation"),
                    ("Backlog", "Backlog"),
                    ("Development", "Development"),
                    ("Testing", "Testing"),
                    ("Deployment", "Deployment"),
                    ("Complete", "Complete"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
