# Generated by Django 4.1.1 on 2022-09-21 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_rename_contact_requestor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="description",
            field=models.TextField(default="test"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="changerequest",
            name="title",
            field=models.CharField(default="test", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Clinical Assessment", "Clinical Assessment"),
                    ("Awaiting Prioritisation", "Awaiting Prioritisation"),
                    ("Backlog", "Backlog"),
                    ("Development", "Development"),
                    ("Testing", "Testing"),
                    ("Deployment", "Deployment"),
                    ("Complete", "Complete"),
                ],
                default=("New", "New"),
                max_length=50,
            ),
        ),
    ]
