# Generated by Django 4.1.1 on 2022-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_changerequest_description_changerequest_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="changerequest",
            name="priority",
            field=models.CharField(
                choices=[
                    ("Highest", "Highest"),
                    ("Very High", "Very High"),
                    ("High", "High"),
                    ("Medium", "Medium"),
                    ("Low", "Low"),
                ],
                default="Low",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
