# Generated by Django 4.1.1 on 2022-09-24 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_changerequest_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="date_requested",
            field=models.DateField(auto_now_add=True),
        ),
    ]
